"""
Gradio demo: side-by-side comparison of base vs fine-tuned model.

Loads pre-computed evaluation results for instant display,
with optional live inference mode.
"""

import json
from pathlib import Path

import gradio as gr

from config import DATA_DIR, TRAINING_DIR

EVAL_RESULTS_FILE = DATA_DIR / "evaluation_results.json"


def load_precomputed_results() -> list[dict]:
    """Load pre-computed evaluation results."""
    if not EVAL_RESULTS_FILE.exists():
        return []
    with open(EVAL_RESULTS_FILE) as f:
        return json.load(f)


def format_json_output(parsed: dict | None, raw: str) -> str:
    """Format model output for display."""
    if parsed:
        return json.dumps(parsed, indent=2)
    return f"[Raw output — not valid JSON]\n\n{raw}"


def get_example_choices(results: list[dict]) -> list[str]:
    """Build dropdown choices from results."""
    choices = []
    for i, r in enumerate(results):
        gt = r.get("ground_truth", {})
        esc = gt.get("escalation_level", "?")
        week = r.get("week_start", f"Example {i+1}")
        choices.append(f"{week} (escalation: {esc})")
    return choices


def display_example(choice: str, results: list[dict]):
    """Display a pre-computed example."""
    if not choice or not results:
        return "", "", "", "", ""

    idx = next(
        (i for i, c in enumerate(get_example_choices(results)) if c == choice),
        0,
    )
    r = results[idx]

    # Input
    test_examples = []
    if (TRAINING_DIR / "test.jsonl").exists():
        with open(TRAINING_DIR / "test.jsonl") as f:
            for line in f:
                if line.strip():
                    test_examples.append(json.loads(line))

    input_text = ""
    if idx < len(test_examples):
        input_text = test_examples[idx]["messages"][1]["content"]
    else:
        input_text = r.get("week_start", "N/A")

    # Base model output
    base = r["base_model"]
    base_output = format_json_output(base.get("parsed_json"), base.get("raw_output", ""))
    base_metrics = base["metrics"]
    base_summary = (
        f"Valid JSON: {'Yes' if base_metrics['valid_json'] else 'No'}\n"
        f"Field completeness: {base_metrics['field_completeness']:.0%}\n"
        f"Escalation error: {base_metrics['escalation_error'] if base_metrics['escalation_error'] is not None else 'N/A'}"
    )

    # Fine-tuned output
    ft = r["finetuned_model"]
    ft_output = format_json_output(ft.get("parsed_json"), ft.get("raw_output", ""))
    ft_metrics = ft["metrics"]
    ft_summary = (
        f"Valid JSON: {'Yes' if ft_metrics['valid_json'] else 'No'}\n"
        f"Field completeness: {ft_metrics['field_completeness']:.0%}\n"
        f"Escalation error: {ft_metrics['escalation_error'] if ft_metrics['escalation_error'] is not None else 'N/A'}"
    )

    # Ground truth
    gt_output = json.dumps(r["ground_truth"], indent=2)

    return input_text, base_output, base_summary, ft_output, ft_summary, gt_output


def build_aggregate_metrics(results: list[dict]) -> str:
    """Build aggregate metrics summary."""
    if not results:
        return "No evaluation results found. Run 06_evaluate.py first."

    lines = []
    for model_name, key in [("Base Model", "base_model"), ("Fine-tuned Model", "finetuned_model")]:
        metrics = [r[key]["metrics"] for r in results]
        valid = sum(1 for m in metrics if m["valid_json"])
        completeness = sum(m["field_completeness"] for m in metrics) / len(metrics)
        esc_errors = [m["escalation_error"] for m in metrics if m["escalation_error"] is not None]
        mae = sum(esc_errors) / len(esc_errors) if esc_errors else float("nan")

        lines.append(f"### {model_name}")
        lines.append(f"- Valid JSON: {valid}/{len(metrics)} ({100*valid/len(metrics):.0f}%)")
        lines.append(f"- Avg field completeness: {completeness:.0%}")
        lines.append(f"- Escalation MAE: {mae:.2f}" if esc_errors else "- Escalation MAE: N/A")
        lines.append("")

    return "\n".join(lines)


ETHICS_TEXT = """
## Ethics & Limitations

### 1. Hallucination Risk
The model may generate specific military details (unit names, weapon systems, troop counts) that are
not present in the GDELT data. In a real intelligence context, this could lead to false threat assessments.

### 2. Training Label Bias
Our training labels were generated by Claude (another LLM), not human intelligence analysts.
The fine-tuned model inherits Claude's analytical framework, biases, and any systematic errors
in its geopolitical reasoning.

### 3. GDELT Source Bias
GDELT overrepresents English-language and Western news sources. Coverage of internal DPRK events
is inherently limited. Events may reflect media attention cycles rather than actual military
activity changes.

### 4. Dual-Use Concerns
An automated geopolitical risk scoring tool could be misused for information warfare,
algorithmic trading on geopolitical events, or justifying predetermined policy positions
with AI-generated "analysis."

### 5. Calibration Limitation
The 1-5 escalation scale was defined and applied by an LLM, not validated against historical
outcomes. This scale should not be treated as a validated early warning indicator.
"""


def create_app():
    results = load_precomputed_results()
    choices = get_example_choices(results)

    with gr.Blocks(title="NK Military Risk Analyst", theme=gr.themes.Soft()) as app:
        gr.Markdown("# NK Military Activity Risk Analyst")
        gr.Markdown(
            "Fine-tuned Llama-3.2-3B-Instruct with QLoRA on GDELT event data. "
            "Compare base model vs. fine-tuned model risk assessments."
        )

        with gr.Tabs():
            with gr.TabItem("Before / After Comparison"):
                if not results:
                    gr.Markdown("**No evaluation results found.** Run the pipeline first:\n"
                               "1. `uv run python 01_fetch_gdelt.py`\n"
                               "2. `uv run python 02_build_clusters.py`\n"
                               "3. `uv run python 03_generate_labels.py`\n"
                               "4. `uv run python 04_prepare_dataset.py`\n"
                               "5. `uv run python 05_finetune.py`\n"
                               "6. `uv run python 06_evaluate.py`")
                else:
                    dropdown = gr.Dropdown(
                        choices=choices,
                        value=choices[0] if choices else None,
                        label="Select test example",
                    )

                    input_box = gr.Textbox(label="Input (GDELT Event Cluster)", lines=10)

                    with gr.Row():
                        with gr.Column():
                            gr.Markdown("### Base Model (Before)")
                            base_output = gr.Textbox(label="Output", lines=20)
                            base_metrics = gr.Textbox(label="Metrics", lines=3)
                        with gr.Column():
                            gr.Markdown("### Fine-tuned Model (After)")
                            ft_output = gr.Textbox(label="Output", lines=20)
                            ft_metrics = gr.Textbox(label="Metrics", lines=3)

                    gr.Markdown("### Ground Truth (Claude-generated label)")
                    gt_output = gr.Textbox(label="Ground Truth", lines=10)

                    dropdown.change(
                        fn=lambda c: display_example(c, results),
                        inputs=[dropdown],
                        outputs=[input_box, base_output, base_metrics, ft_output, ft_metrics, gt_output],
                    )

                    # Load first example on start
                    app.load(
                        fn=lambda: display_example(choices[0], results) if choices else ("", "", "", "", "", ""),
                        outputs=[input_box, base_output, base_metrics, ft_output, ft_metrics, gt_output],
                    )

            with gr.TabItem("Aggregate Metrics"):
                gr.Markdown(build_aggregate_metrics(results))

            with gr.TabItem("Ethics & Limitations"):
                gr.Markdown(ETHICS_TEXT)

            with gr.TabItem("About"):
                gr.Markdown("""
## Project Overview

**Task**: Fine-tune an LLM to act as a geopolitical risk analyst for North Korean military activity.

**Data Source**: GDELT v2 (Global Database of Events, Language, and Tone) — structured event data
extracted from worldwide news, coded using the CAMEO taxonomy.

**Model**: Llama-3.2-3B-Instruct, fine-tuned with QLoRA (4-bit quantization + Low-Rank Adaptation)

**Training Pipeline**:
1. Pull NK military events from GDELT via BigQuery
2. Group events into weekly clusters
3. Generate expert risk assessment labels using Claude (knowledge distillation)
4. Fine-tune Llama-3.2-3B with QLoRA on the labeled data
5. Evaluate with before/after comparison on held-out test set

**Key Metric**: The fine-tuned model produces structured JSON risk assessments with escalation
levels, while the base model outputs unstructured text.
""")

    return app


if __name__ == "__main__":
    app = create_app()
    app.launch()
